name: woobox
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^4.4.10

  # BASE
  intl: 0.17.0

  # FIREBASE PACKAGES
#  firebase_crashlytics: ^2.1.1
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  firebase_remote_config: ^0.11.0+2

  # UI
  flutter_vector_icons: ^1.0.0
  dotted_border: ^2.0.0+1
  flutter_rating_bar: ^4.0.0
  otp_text_field: ^1.1.1
  flutter_staggered_grid_view: ^0.4.1
  country_code_picker: ^2.0.2
  html: ^0.15.0
  flutter_html: ^2.1.5
  package_info: ^2.0.2

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.2.7

  # STATE MANAGEMENT
  provider: ^6.0.1
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2

  # ADS
  google_mobile_ads: ^1.0.0

  # IMAGES
  image_picker: ^0.8.4+4
  cached_network_image: ^3.1.0+1
  photo_view: ^0.13.0

  # AUTHENTICATION
  google_sign_in: ^5.2.1
  the_apple_sign_in: ^1.1.1

  # CONNECTIVITY
  http: ^0.13.4
  connectivity: ^3.0.6
  share: ^2.0.4

  #TOOLS
  google_fonts: ^2.1.0

  # WEB TOOLS
  webview_flutter: ^2.3.1

  # PAYMENTS
  razorpay_flutter: ^1.2.7
  # flutter_pay: ^1.0.2

  # LAUNCH URL
  url_launcher: ^6.0.15

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.4
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_launcher_icons_maker: ^0.10.2
  change_app_package_name: ^1.1.0

flutter_icons:
  image_path: 'images/woobox/ic_app_icon.png'
  android: true
  

flutter:

  uses-material-design: true

  assets:
    - images/woobox/
    - lang/
    - assets/